### ISSUE TITLE
Add prices for preemptible instances

### ISSUE THREAD

**Issue by gdubicki** [Cyclenerd/google-cloud-compute-machine-types#12]
**Is your feature request related to a problem? Please describe.**
 
I want to compare E2 vs N2D preemptible instances across a few regions using your tool and I can't because it doesn't include preemptible prices at all. 

**Describe the solution you'd like**

Add a column within the "Costs" group with the preemptible price.

**Describe alternatives you've considered**

Using an alternative solution - https://gcpinstances.doit-intl.com - but it has its own issue with no guarantee of data being up to date (see https://github.com/doitintl/gcpinstances.info/issues/34 for more info).

**Comment by Cyclenerd** [comment]
Currently you can only filter if the instance (machine type) is available as spot (Spot Provisioning Mode). By the way, prices are calculated automatically with this tool: https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator

For Spot there is already a little bit prepared but not yet implemented. 

https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/blob/master/build/mapping.csv#L176

Pull requests are welcome. I don't use spot VMs so I can't control the real calculation that is later on the invoice.

**Comment by Cyclenerd** [comment]
Prices for Spot VMs are now displayed.
