### ISSUE TITLE
Allow sorting on spot instance pricing

### ISSUE THREAD

**Issue by AndrewVSutherland** [Cyclenerd/google-cloud-compute-machine-types#13]
It would be great if on the web page for a particular machine type there was an option to sort by spot instance price (this sort order is often suprisingly different!).

**Comment by Cyclenerd** [comment]
Hi,

Good idea. I have added a few more sorting options.

Depending on the caching you should see it in the next hours.

![image](https://github.com/Cyclenerd/google-cloud-compute-machine-types/assets/176242/ccb081f7-42a7-4375-be3e-96d2194d772c)

![image](https://github.com/Cyclenerd/google-cloud-compute-machine-types/assets/176242/b8248f96-437a-4890-8617-8c1ccdaf3b7d)

For your analysis, however, I recommend the Instance Picker:
<https://gcloud-compute.com/grid.html>

BR Nils

**Comment by AndrewVSutherland** [comment]
This is just what I wanted, thank you!
