### ISSUE TITLE
Bug: Header T2D and T2A on regions.html mixed up

### ISSUE THREAD

**Issue by muffl0n** [Cyclenerd/google-cloud-compute-machine-types#15]
**Describe the bug**
On page https://gcloud-compute.com/regions.html the column headers for T2D and T2A are mixed up.
Order of column headers is T2A then T2D. But order of data columns is T2D then T2A.

```
# http -p b https://gcloud-compute.com/regions.html | grep -E 'T2(D|A)' | head -4
<th scope="col">T2A</th>
<th scope="col">T2D</th>
<td title="Instance Picker with filter on machine type series T2D in region asia-east1">
<td class="table-danger" title="Instance Picker with filter on machine type series T2A in region asia-east1">
```

**Comment by Cyclenerd** [comment]
Thanks for reporting. Fixed with https://github.com/Cyclenerd/google-cloud-compute-machine-types/commit/615b812204010296d9cf7c880cdbfb7bc893f1c0. Will be online next Friday.
