### ISSUE TITLE
Bug: C2D network bandwidth incorrect for 2,4, 8 vCPU shapes

### ISSUE THREAD

**Issue by dutchiechris** [Cyclenerd/google-cloud-compute-machine-types#16]
**Describe the bug**
c2d family show 32 Gbps network limit for all shapes, but the 2 and 4 vCPU shapes should be 10, and the 8 vCPU shape should be 16.  See https://cloud.google.com/compute/docs/compute-optimized-machines#c2d_machine_types

**Comment by Cyclenerd** [comment]
Thank you. It is fixed.
