### ISSUE TITLE
Bug: Inconsistent measurement unit for memory - GB or GiB

### ISSUE THREAD

**Issue by zifter** [Cyclenerd/google-cloud-compute-machine-types#20]
**Describe the bug**
In different places different measurement units are used to describe memory, but the same amount are used.

**To Reproduce**
1. Look at here - GB. https://gcloud-compute.com/instances.html@
2. Dowload csv, find column called memoryGiB

What is true? GB or GiB?

**Expected behavior**
Consistent measurement unit

**Comment by Cyclenerd** [comment]
I have joined the inconsistent naming of Google ;-) The website says GB in the billing API however gibibyte (`...USD per 1 gibibyte hour`).

The memory is in my opinion JEDEC binary gigabytes (GB). A test with e2-micro shows:

```bash
echo $(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / (1024 * 1024)))
```
973

GB:
```bash
free --giga -h
```

```text
               total        used        free      shared  buff/cache   available
Mem:            1.0G        334M        367M        454K        472M        686M
```

GiB:
```bash
free --gibi -h
```

```text
               total        used        free      shared  buff/cache   available
Mem:           973Mi       319Mi       350Mi       444Ki       450Mi       654Mi
```

I have renamed all GiB to GB: https://github.com/Cyclenerd/google-cloud-compute-machine-types/commit/e51a0a182e425cbff09fb504f1595aa5c5e64931
