### ISSUE TITLE
Bug: monthly price for n1-highmem-2 is wrong for europe-west1

### ISSUE THREAD

**Issue by skadefro** [Cyclenerd/google-cloud-compute-machine-types#24]
There seem to be an issue with your monthly price for n1-highmem-2 in europe-west1
if you filter by europe-west1 and set minimum ram to 13 try and order by cheapest by month
then compare the top 2 ( n1-highmem-2 and e2-highmem-2 )

Most price calculators use 730 hours for one month, so that is what i used below
for n1-highmem-2 you have $0.1301 that's $94.973 per month ( you have $66.5 )
for e2-highmem-2 you have $0.0994 that's $72.562 per month ( you have $72.59 )

So i went to https://cloud.google.com/products/calculator and compared. This pages says
n1-highmem-2 to be $95 per month
e2-highmem-2 to be $72.59 per month

**Comment by Cyclenerd** [comment]
I think my calc is correct. Google no longer automatically subtracts SUD on many pages. Machine type N1 gets SUD (https://cloud.google.com/compute/docs/sustained-use-discounts) E2 not.

**Comment by skadefro** [comment]
aaahhhh, that makes sense. So your monthly price is including SUD ?

**Comment by Cyclenerd** [comment]
Yes, price per month is with sustained use discount (SUD) if available.
