### ISSUE TITLE
Feature request: Add Mexico region northamerica-south1

### ISSUE THREAD

**Issue by zifter** [Cyclenerd/google-cloud-compute-machine-types#31]
**Is your feature request related to a problem? Please describe.**
Luck of information about Mexico which was released 18th of November

**Describe the solution you'd like**
Add new region

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Cyclenerd** [comment]
Documented and processed in: https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/issues/253

**Comment by zifter** [comment]
How fast it will be on https://gcloud-compute.com/regions.html?

**Comment by Cyclenerd** [comment]
today.

**Comment by zifter** [comment]
https://github.com/Cyclenerd/google-cloud-compute-machine-types/actions/runs/11918444158/job/33215878974
looks like something went wrong with publishin website - duration is already more then 1 hour and 36 minutes
