### ISSUE TITLE
Add metric "benchmark points per $"

### ISSUE THREAD

**Issue by muffl0n** [Cyclenerd/google-cloud-compute-machine-types#8]
The metrics already contain a value "benchmark". We found a metric "benchmark points per $" really useful while evaluating which instance type to pick.

Do you think it would be easy to add such a (virtual) metric?

Thank you very much for your awesome project! It really makes our life easier! 😍

**Comment by Cyclenerd** [comment]
Good idea. I added benchmark divided by price per hours (https://github.com/Cyclenerd/google-cloud-compute-machine-types/commit/62a4f76784c59658f48fd4356e8d44b5f4b3f850). You can also make further evaluations with the SQL or CSV export.

The T2D family has a good price per CPU performance ratio.

![image](https://user-images.githubusercontent.com/176242/170864362-093966e2-124f-42bf-9f8a-b28b0b104c28.png)

I would also be happy if you give the repo a star :)

**Comment by muffl0n** [comment]
Thank you very much for adding it so quickly! Unfortunately, I can't find the new values on https://gcloud-compute.com/instances.html
The build ran without a problem, right? I'm confused. :)

**Comment by Cyclenerd** [comment]
You can find it in the Instance Picker (gcloud-compute.com/grid.html).
