### ISSUE TITLE
C2D and E2 benchmarks results are missing

### ISSUE THREAD

**Issue by gdubicki** [Cyclenerd/google-cloud-compute-machine-types#9]
Hi!

Thanks for a very promising tool! I was using https://gcpinstances.doit-intl.com till now but your solution seems to be even better!

However you seem to be missing C2D benchmarks results.

(I have just added them to gcpinstances.doit-intl.com in https://github.com/doitintl/gcpinstances.info/pull/29 as they were missing it too, so perhaps you can reuse that PR to add it to your app. Or just take it from the source, of course. :))

**Comment by gdubicki** [comment]
*Update*: same problem with E2 benchmarks.

**Comment by Cyclenerd** [comment]
https://github.com/Cyclenerd/google-cloud-compute-machine-types/commit/64027869e9ee7a8d7f8f37de4f7a108cc783b2eb

**Comment by Cyclenerd** [comment]
Thank you very much for the info. It's great that Google has published new benchmarks. I first tried to update it manually, but then I wrote a script for it. Values should be up to date now.

**Comment by gdubicki** [comment]
Thanks for the immediate response! :D 

..but there is a small bug in the data you added - for c2d-highcpu-32 the value in https://github.com/Cyclenerd/google-cloud-compute-machine-types/commit/64027869e9ee7a8d7f8f37de4f7a108cc783b2eb#diff-87ad5162aab9f1858a82af56081c00f4040c9393d9a69c47773b57c3f63438c4R130 is `656,02` while it should be `656,020`.

**Comment by gdubicki** [comment]
There are more invalid values - f.e. here https://github.com/Cyclenerd/google-cloud-compute-machine-types/commit/64027869e9ee7a8d7f8f37de4f7a108cc783b2eb#diff-87ad5162aab9f1858a82af56081c00f4040c9393d9a69c47773b57c3f63438c4R27-R28 .

I think that the problem occurs when the value has trailing zeros.

**Comment by Cyclenerd** [comment]
Thank you so much for checking this. My localization in LibreOffice played a trick on me. I have again copied and exported everything. Now, everything should be totally up-to-date and correct. *(fingers crossed)*

» https://gcloud-compute.com/c2d-highcpu-32.html
